org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.17
kotlin_version=2.4.10
foojay_resolver_version=1.0.0

mod_version=1.0.1
maven_group=de.xclipsen
archives_base_name=xclipsen-mod

fabric_version=0.155.2+26.1.2
fabric_kotlin_version=1.13.13+kotlin.2.4.10
hypixel_mod_api_version=1.0.2+build.1+mc26.1
hypixel_mod_api_core_version=1.0.2
jda_version=6.3.2
shadow_version=9.4.1
slf4j_version=2.0.17
gson_version=2.13.2
